import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Dragon UI</title>
        <meta name="Clone of SpaceX's Dragon, in-flight UI/UX controls" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SpaceX Dragon UI
        </h1>
      </main>
    </div>
  )
}

export default Home
