import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/app.module.css";
import VehicleOverview from "./vehicle-overview";

const App: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Dragon UI</title>
        <meta
          name="Clone of SpaceX's Dragon, in-flight UI/UX controls"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <VehicleOverview />
    </div>
  );
};

export default App;
